title: DotConnect
google_analytics: UA-9386106-6

facebook_username: groups/dotcong
github_username: DotConnectOrg
rss: rss

show_excerpts: true

disqus:
  shortname: dotconnect

theme: minima
header_pages:
  - events/index.md
  - groups/index.md
  - blog/index.md
  - connect.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

