title: DotConnect
google_analytics: UA-9386106-6

github_username: DotConnectOrg
rss: rss

show_excerpts: true

theme: minima
header_pages:
  - events/index.md
  - member-groups/index.md
  - blog/index.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

